# Exercise 02: Data Structures & for-Loops

## Lists & Loops
Based on the two lists of programming languages below, create a new list containing only the yet unknown languages. Sort the resulting list alphabetically and print it.

In [2]:
programming_languages = [
    "Python", 
    "C", 
    "Julia", 
    "Java", 
    "C#", 
    "Fortran", 
    "C++", 
    "JavaScript",
    "Perl",
    "Lisp",
]

languages_i_know = ["Python", "Julia", "C"]

# your code goes here:
unknown_programming_languages = programming_languages[:]
for language in languages_i_know:
    unknown_programming_languages.remove(language)
print(sorted(unknown_programming_languages))

# If you already know "if":
unknown_programming_languages = []
for language in programming_languages:
    if language not in languages_i_know:
        unknown_programming_languages.append(language)
print(sorted(unknown_programming_languages))


['C#', 'C++', 'Fortran', 'Java', 'JavaScript', 'Lisp', 'Perl']
['C#', 'C++', 'Fortran', 'Java', 'JavaScript', 'Lisp', 'Perl']


### Sets
Solve the above example with sets instead of loops!

In [3]:
# your code goes here:
unknown_programming_languages = set(programming_languages) - set(languages_i_know)
print(sorted(unknown_programming_languages))

['C#', 'C++', 'Fortran', 'Java', 'JavaScript', 'Lisp', 'Perl']


<summary>
<detaisl>

## Data structure conversion
Create a dictionary which maps product names to prices, using the `price_table` given below.

In [4]:
price_table = [("honey", 2.45), ("butter", 1.30), ("catfood", 4.85), ("tea", 1.50)]

# your code goes here:
products = {}

for name, price in price_table:
    products[name] = price
print(products)

# Alternative:
print(dict(price_table))

{'honey': 2.45, 'butter': 1.3, 'catfood': 4.85, 'tea': 1.5}
{'honey': 2.45, 'butter': 1.3, 'catfood': 4.85, 'tea': 1.5}


## Nested data structures
The data below is given as a list of nested tuples, where each outer tuple is structured as follows:

`(<name>, (<price>, <amount>))`

Transform the data into a more explicit form, a dictionary where each key is a product name and each value is again a dictionary containing entries for `"price"` and `"amount"`. The result should look like this:
```python
{'honey': {'price': 2.45, 'amount': 10}, 'butter': {'price': 1.3, 'amount': 100}, 'catfood': {'price': 4.85, 'amount': 3}, 'tea': {'price': 1.5, 'amount': 123}}
```

In [19]:
input_data = [
    ("honey", (2.45, 10)), 
    ("butter", (1.30, 100)), 
    ("catfood", (4.85, 3)), 
    ("tea", (1.50, 123)),
]

# your code goes here:
products = {}
for name, (price, amount) in input_data:
    products[name] = {
        "price": price,
        "amount": amount,
    }
print(products)

{'honey': {'price': 2.45, 'amount': 10}, 'butter': {'price': 1.3, 'amount': 100}, 'catfood': {'price': 4.85, 'amount': 3}, 'tea': {'price': 1.5, 'amount': 123}}


Finally, reduce the amount of butter by `20` and print the entire dictionary:

In [20]:
# your code goes here:
products["butter"]["amount"] -= 20
print(products)

{'honey': {'price': 2.45, 'amount': 10}, 'butter': {'price': 1.3, 'amount': 80}, 'catfood': {'price': 4.85, 'amount': 3}, 'tea': {'price': 1.5, 'amount': 123}}
